[package]
name = "rust-pepperbot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = "0.22.3"
reqwest = "0.11.14"
rss = "2.0.2"
teloxide = { version = "0.12.2", features = ["macros"] }
thiserror = "1.0.39"
tokio = { version = "1.26.0", features = ["full"] }
