name: Build

on: [push]

jobs:
  x86_64-unknown-linux-gnu:
    name: Linux x86_64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target x86_64-unknown-linux-gnu --bins --release
      - name: Rename binaries
        run: mv message-queuing message-queuing_amd64 && mv bot-commands bot-commands_amd64 && mv bot-consumer bot-consumer_amd64
      - name: Upload AMD64 binaries
        uses: actions/upload-artifact@v3
        with:
          name: amd64
          path: "*_amd64"

  aarch64-unknown-linux-gnu:
    name: Linux ARM64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-gnu
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target aarch64-unknown-linux-gnu --bins --release
      - name: Rename binaries
        run: mv message-queuing message-queuing_arm64 && mv bot-commands bot-commands_arm64 && mv bot-consumer bot-consumer_arm64
      - name: Upload ARM64 binaries
        uses: actions/upload-artifact@v3
        with:
          name: arm64
          path: "*_arm64"

  docker:
    name: Docker Image
    runs-on: ubuntu-latest
    needs: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
#      - name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Download AMD64 binaries
        uses: actions/download-artifact@v3
        with:
          name: amd64
      - name: Download ARM64 binaries
        uses: actions/download-artifact@v3
        with:
          name: arm64
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
#          push: true
          tags: marnixjanssen/telgram-pepperbot:latest
#          cache-from: type=gha
#          cache-to: type=gha,mode=max
